# Generated by Django 2.2.4 on 2020-06-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='teacher',
        ),
        migrations.RenameField(
            model_name='classassignment',
            old_name='assignment_name',
            new_name='Question',
        ),
        migrations.DeleteModel(
            name='MessageToTeacher',
        ),
        migrations.DeleteModel(
            name='StudentMarks',
        ),
    ]
